### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by sebasptsch** [DOMjudge/domjudge-packaging#149]
I'm trying to setup domjudge in docker and it is failing immediately after the migration script. 

Domserver is exiting with the message `No module named 'requests'`

```
domserver    | [info] ++ migrating DoctrineMigrations\Version20230122162836 (Drop enabled from external contest sources and make cid unique)
domserver    | [info] Migration DoctrineMigrations\Version20230122162836 migrated (took 33.7ms, used 58.5M memory)
domserver    | [notice] finished in 7031.8ms, used 58.5M memory, 62 migrations executed, 315 sql queries
domserver    |
domserver    |
domserver    |    > loading App\DataFixtures\DefaultData\ExecutableFixture
domserver    |    > loading App\DataFixtures\DefaultData\LanguageFixture
domserver    |    > loading App\DataFixtures\DefaultData\RoleFixture
domserver    |    > loading App\DataFixtures\DefaultData\TeamCategoryFixture
domserver    |    > loading App\DataFixtures\DefaultData\TeamFixture
domserver    |    > loading App\DataFixtures\DefaultData\UserFixture
domserver    |
domserver    |    > loading App\DataFixtures\ExampleData\JudgehostFixture
domserver    |    > loading App\DataFixtures\ExampleData\TeamAffiliationFixture
domserver    |    > loading App\DataFixtures\ExampleData\TeamCategoryFixture
domserver    |    > loading App\DataFixtures\ExampleData\TeamFixture
domserver    |    > loading App\DataFixtures\ExampleData\UserFixture
domserver    | Traceback (most recent call last):
domserver    |   File "/opt/domjudge/domserver/bin/import-contest", line 27, in <module>
domserver    |     import dj_utils
domserver    |   File "/opt/domjudge/domserver/lib/dj_utils.py", line 10, in <module>
domserver    |     import requests
domserver    | ModuleNotFoundError: No module named 'requests'
domserver    | [!!] Start script 50-domjudge.sh failed
domserver exited with code 1
```

**Comment by nickygerritsen** [comment]
Ah yes we need this package nowadays. What version are you running? I will add the package

**Comment by sebasptsch** [comment]
The latest docker version
